# Setup
title: EyeLight Data Scidence Lab
url: https://eyelightlab.github.io/
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Young Kook Kim, MD, PhD
  url: https://snucm.elsevierpure.com/en/persons/y-kim-41
  email: eyedry@snu.ac.kr

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Research Profile
    url: https://snucm.elsevierpure.com/en/persons/y-kim-41

  - title: Seoul National University Hospital (SNUH)
    url: http://www.snuh.org/global/en/blog/01089/paper.do?scsContCnt=0&schContCnt=0&carContCnt=0&socContCnt=0&dr_cd=01089
